---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/v2 abstract figure/v2 abstract figure.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/173169/articles/206447/master/file/figures/v2%20abstract%20figure/v2%20abstract%20figure.png"
    folder_url: "/users/173169/articles/206447/master/folder/figures/v2 abstract figure"
